-- ============================================================
--  IDI · Dia a Dia — BANCO DE DADOS (rode no Supabase)
-- ============================================================
--  Como rodar:
--  1. Entre em supabase.com → seu projeto
--  2. Menu esquerdo → SQL Editor → + New query
--  3. COLE TUDO ISTO e clique em RUN
--  Pronto. As 3 tabelas abaixo passam a alimentar o site.
-- ============================================================


-- ── 1. VISITANTES (formulário da página de entrada / splash) ──
create table if not exists visitantes (
  id         bigint generated by default as identity primary key,
  nome       text not null,
  email      text not null,
  whatsapp   text,
  pais       text,
  cidade     text,
  origem     text default 'splash',
  criado_em  timestamptz default now()
);

alter table visitantes enable row level security;

-- Qualquer visitante pode SE CADASTRAR (inserir), mas ninguém anônimo
-- consegue LER a lista. Você lê pelo painel do Supabase (logado).
drop policy if exists "visitantes_insert" on visitantes;
create policy "visitantes_insert" on visitantes
  for insert to anon, authenticated with check (true);


-- ── 2. CAMPANHA (a barra de arrecadação — valor REAL) ──
create table if not exists campanha (
  id          bigint primary key,
  titulo      text default 'Campanha 2026',
  meta        bigint default 1500000,   -- meta em reais (número inteiro)
  arrecadado  bigint default 0,         -- VOCÊ atualiza este número
  atualizado  timestamptz default now()
);

alter table campanha enable row level security;

-- Todos podem LER (a barra do site lê isto). Só você (logado) edita.
drop policy if exists "campanha_select" on campanha;
create policy "campanha_select" on campanha
  for select to anon, authenticated using (true);

-- Cria a linha inicial (id = 1). Mude "arrecadado" conforme os PIX chegam.
insert into campanha (id, titulo, meta, arrecadado)
values (1, 'Campanha 2026', 1500000, 0)
on conflict (id) do nothing;


-- ── 3. DOACOES (intenções de doação — para follow-up) ──
create table if not exists doacoes (
  id         bigint generated by default as identity primary key,
  nome       text,
  email      text,
  whatsapp   text,
  valor      bigint,
  metodo     text,                      -- 'pix' ou 'whatsapp'
  status     text default 'intencao',   -- intencao | confirmada | recusada
  criado_em  timestamptz default now()
);

alter table doacoes enable row level security;

drop policy if exists "doacoes_insert" on doacoes;
create policy "doacoes_insert" on doacoes
  for insert to anon, authenticated with check (true);


-- ============================================================
--  PRONTO. Agora:
--
--  • Ver quem se cadastrou:
--      Menu Table Editor → tabela "visitantes"
--      (dá pra exportar CSV pelo botão de exportar)
--
--  • Atualizar a barra de arrecadação:
--      Table Editor → "campanha" → linha id=1 →
--      edite o campo "arrecadado" e salve. A barra do site muda na hora.
--
--  • Ver quem clicou em doar:
--      Table Editor → "doacoes"
-- ============================================================
